[982]: Create SoprtTypeCard Component in Storybook
gumennii/w-dotcom pull request #3
Opened 2023-12-20 11:11 UTC by aceaicovski

Ticket: https://trello.com/c/OfaYep82/981-component-sport-type-card
Design reference: https://www.figma.com/file/LqRSCt5qTzvzKAyNBeMStv/Design-System?node-id=2360%3A10744&mode=dev

2023-12-20 16:24 UTC, yevhen33 commented on src/components/SportTypeCard/SportTypeCardTitle.tsx
> +        "text-center text-[33px] font-bold uppercase leading-[42.90px]",
Не далай таких значений text-[33px], все значения берем из tailwind, это text-3xl или text-4xl посмотри что лучше смотрится

2023-12-20 16:29 UTC, aceaicovski commented on src/components/SportTypeCard/SportTypeCardTitle.tsx
> +        "text-center text-[33px] font-bold uppercase leading-[42.90px]",
Хорошо, исправила!

2023-12-21 01:44 UTC, gumennii requested changes

2023-12-21 01:44 UTC, gumennii commented on src/components/SportTypeCard/SportTypeCard.tsx
> +import cn from "~/utils/style";
@yevhen33 , @aceaicovski , давайте соблюдать порядок импорта компонентов
1. Внешние компоненты
2. Наши компоненты переиспользуемые (шлобальные)
3. Компоненты локальные для компонента самого

2023-12-21 01:44 UTC, gumennii commented on src/components/SportTypeCard/SportTypeCard.tsx
> +  variant?: "vertical" | "horizontal";
А откуда у нас эти варианты? На мобильной версии там просто оторбражаются они иначе, но наверное это никак не вариант. Или я чего-то не вижу?

2023-12-21 01:44 UTC, gumennii commented on src/components/SportTypeCard/SportTypeCardTitle.tsx
> +  const Tag = tag;
Я не думаю что в этом компоненте будет меняться HTML TAG, выглядит сложнее чем должно быть

2023-12-21 01:44 UTC, gumennii commented on src/components/SportTypeCard/SportTypeCardTitle.tsx
> +  const Tag = tag;
Я не думаю что тут вообще нужен отдельный компонент

2023-12-21 01:44 UTC, gumennii commented on src/components/SportTypeCard/SportTypeCard.stories.tsx
> +const IconPlaceholder = () => {
А чего не используем FontAwesome Icons?

2023-12-21 01:44 UTC, gumennii commented on src/components/SportTypeCard/SportTypeCard.tsx
> +  horizontal: "p-4 rounded-2xl shadow flex justify-center items-center gap-4",
Так а для чего эти варианты?

2023-12-21 01:44 UTC, gumennii commented on src/components/SportTypeCard/SportTypeCard.tsx
> +  children: ReactNode;
А может лучше PropsWithChildren?

2023-12-21 01:44 UTC, gumennii commented on src/components/SportTypeCard/SportTypeCard.stories.tsx
> +      <FontAwesomeIcon icon={faFootball} className="h-10 w-10 p-1 " />
То есть тут у нас иконка будет всегда футбольная?

2023-12-21 11:38 UTC, aceaicovski commented on src/components/SportTypeCard/SportTypeCard.tsx
> +  variant?: "vertical" | "horizontal";
<img width="780" alt="Screenshot 2023-12-21 at 13 33 19" src="https://github.com/gumennii/w-dotcom/assets/77005768/d2b2f1f5-86cf-48f7-a0f6-5e3021aada8d">
В дизайне дали названиям этим изображениям Vertical / Horizontal, вот я и подумала что это варианты. Уже убрала этот проп и изменила стили чтобы менялось по ширине экрана.

2023-12-21 19:37 UTC, closed without merging